```{r}
#| label: sol-set-up
#| message: false
#| warning: false
#| include: false
library(tidyverse)
library(survey)
library(srvyr)
library(srvyrexploR)
```

```{r}
#| label: sol-design-obj
#| include: false

anes_des <- anes_2024 %>%
  filter(InterviewMode_Pre != "3. Paper (PAPI)") %>% 
  mutate(Weight = V240108b / sum(V240108b) * 232449541) %>%
  as_survey_design(
    weights = Weight,
    strata = V240108d,
    ids = V240108c,
    nest = TRUE
  )
```

### Exercises

1. Is there a relationship between party identification (`PartyID`) and whether people voted early (`EarlyVote2024`)?

```{r}
#| label: testing-sol-1
#| code-fold: true
#| code-summary: "Show code"

anes_des %>%
  filter(!is.na(PartyID), !is.na(EarlyVote2024)) %>%
  group_by(PartyID, EarlyVote2024) %>%
  summarize(
    p = survey_mean()
  )

anes_des %>%
  filter(!is.na(PartyID), !is.na(EarlyVote2024)) %>%
  svychisq(~ EarlyVote2024 + PartyID, design = .)
```

2. Is there a relationship between party identification (`PartyID`) and trust in the government (`TrustGovernment`)? Use Wald as the `statistic` option.

```{r}
#| label: testing-sol-2
#| code-fold: true
#| code-summary: "Show code"

anes_des %>%
  filter(!is.na(PartyID), !is.na(TrustGovernment)) %>%
  group_by(PartyID, TrustGovernment) %>%
  summarize(
    p = survey_mean()
  )

anes_des %>%
  filter(!is.na(PartyID), !is.na(TrustGovernment)) %>%
  svychisq(~ TrustGovernment + PartyID, design = ., statistic = "Wald")
```

3. Is there a difference in the distribution of sex (`Sex`) across early voting status (`EarlyVote2024`)?

```{r}
#| label: testing-sol-3
#| code-fold: true
#| code-summary: "Show code"

anes_des %>%
  filter(!is.na(Sex), !is.na(EarlyVote2024)) %>%
  group_by(Sex, EarlyVote2024) %>%
  summarize(
    p = survey_mean()
  )

anes_des %>%
  filter(!is.na(Sex), !is.na(EarlyVote2024)) %>%
  svychisq(~ Sex + EarlyVote2024, design = ., statistic = "Wald")
```
