### Set-up

#### Load necessary packages

```{r}
#| label: set-up
#| message: false
#| warning: false
library(tidyverse)
library(survey)
library(srvyr)
library(srvyrexploR)
library(broom)
library(gt)
```

#### Load in data and preview it

```{r}
#| label: data-summary
glimpse(anes_2024)
```

Find codebook here: [ANES 2024](https://tidy-survey-r.github.io/srvyrexploR/reference/anes_2024.html)

#### Create design objects for usage

```{r}
#| label: design-obj

anes_des <- anes_2024 %>%
  filter(InterviewMode_Pre != "3. Paper (PAPI)") %>% 
  mutate(Weight = V240108b / sum(V240108b) * 232449541) %>%
  as_survey_design(
    weights = Weight,
    strata = V240108d,
    ids = V240108c,
    nest = TRUE
  )
```

### Exercises

1. Build a logistic model predicting early voting in 2020 (`EarlyVote2024`) using age (`Age`), education (`Education`), and party identification (`PartyID`). Include two-way interactions.

```{r}
earlyvote_mod <- anes_des %>%
  filter(!is.na(EarlyVote2024)) %>%
  svyglm(
    design = .,
    formula = EarlyVote2024 ~ (Age + Education + PartyID)^2,
    family = quasibinomial
  )

tidy(earlyvote_mod) %>% print(n = 50)
```

